"""add image_url to words

Revision ID: d5a8a7725d0a
Revises: eb0d7cc50e54
Create Date: 2026-01-04 19:36:46.972343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd5a8a7725d0a'
down_revision: Union[str, None] = 'eb0d7cc50e54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_level_words_id', table_name='level_words')
    op.drop_table('level_words')
    op.drop_index('ix_words_id', table_name='words')
    op.drop_table('words')
    op.drop_index('ix_levels_id', table_name='levels')
    op.drop_table('levels')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_login_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_active_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('tts_rate', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('streak_days', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_login_days', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('points', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('badges', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('achievements', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('total_time_spent', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('courses_completed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey')
    )
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_table('levels',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('levels_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('difficulty', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='levels_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_levels_id', 'levels', ['id'], unique=False)
    op.create_table('words',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('words_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('phonetics', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('syllables', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('difficulty', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('level_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], name='words_level_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='words_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_words_id', 'words', ['id'], unique=False)
    op.create_table('level_words',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('word_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('level_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('attempts', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('correct_attempts', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('mastery_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('is_mastered', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('last_similarity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('last_practiced_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], name='level_words_level_id_fkey'),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], name='level_words_word_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='level_words_pkey')
    )
    op.create_index('ix_level_words_id', 'level_words', ['id'], unique=False)
    # ### end Alembic commands ###
