from io import BytesIO
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.colors import black, grey
from reportlab.lib.units import inch


def build_mock_pdf(attempt, username: str, next_level_unlocked: bool) -> BytesIO:
    buffer = BytesIO()
    pdf = canvas.Canvas(buffer, pagesize=A4)
    width, height = A4
    y = height - 60

    def draw(text, size=11, bold=False, gap=16):
        nonlocal y
        pdf.setFont("Helvetica-Bold" if bold else "Helvetica", size)
        pdf.setFillColor(black)
        pdf.drawString(60, y, text)
        y -= gap

    def divider():
        nonlocal y
        pdf.setStrokeColor(grey)
        pdf.line(60, y, width - 60, y)
        y -= 18

    # ================= HEADER =================
    draw("DYSLEXIA EMPOWERHUB", 18, True, 24)
    draw("Mock Test Performance Report", 14, True, 22)
    draw(f"Attempt ID: {attempt.public_attempt_id}")
    draw(f"Generated On: {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}")
    divider()

    # ================= USER DETAILS =================
    draw("Candidate Information", 13, True, 20)
    draw(f"Username: {username}")
    draw(f"User ID: {attempt.user_id}")
    draw(f"Level: {attempt.level_id}")
    draw(f"Status: {attempt.status.capitalize()}")
    divider()

    # ================= SUMMARY =================
    total_score = attempt.total_score or 0
    verdict = attempt.verdict.replace("_", " ").title()

    draw("Performance Summary", 13, True, 20)
    draw(f"Final Score: {total_score}%")
    draw(f"Verdict: {verdict}")
    draw(f"Confidence Index: {round(total_score/100, 2)}")
    divider()

    results = attempt.results or {}
    words = results.get("words", [])

    draw("Word Breakdown", 13, True, 20)

    for i, w in enumerate(words, 1):
        draw(
            f"{i}. {w.get('expected')} → {w.get('recognized')} "
            f"| Score: {w.get('score')}% | {w.get('verdict')}",
            size=10,
            gap=14
        )

        feedback = w.get("feedback")
        if feedback:
            draw(f"    Feedback: {feedback}", size=9, gap=14)

        if y < 100:
            pdf.showPage()
            y = height - 60

    divider()

    # ================= INSIGHTS =================
    weak = [w for w in words if w.get("score", 0) < 65]
    strong = [w for w in words if w.get("score", 0) >= 85]

    draw("Insights & Observations", 13, True, 20)

    if strong:
        draw(f"Strength: Strong pronunciation in {len(strong)} word(s)")
    if weak:
        draw(f"Improvement Needed: {len(weak)} word(s) require focused practice")
    if not weak:
        draw("Excellent consistency across all words")

    divider()

    # ================= PROGRESSION =================
    draw("Progression Status", 13, True, 20)

    unlock_text = "UNLOCKED" if next_level_unlocked else "LOCKED"
    draw(f"Next Level Eligibility: {unlock_text}")

    if not next_level_unlocked:
        draw("Recommendation: Achieve at least 70% average score to unlock next level")

    divider()

    # ================= RECOMMENDATIONS =================
    draw("Recommended Next Steps", 13, True, 20)

    draw("• Practice weak words slowly with syllable emphasis")
    draw("• Use repetition before recording")
    draw("• Focus on clarity over speed")
    draw("• Attempt mock again after revision")

    divider()

    # ================= FOOTER =================
    pdf.setFont("Helvetica-Oblique", 9)
    pdf.setFillColor(grey)
    pdf.drawString(
        60,
        40,
        "Generated by Dyslexia EmpowerHub • One sound at a time, one step forward."
    )
    pdf.drawString(
        60,
        28,
        "Confidential Report — For learner use only"
    )

    pdf.save()
    buffer.seek(0)
    return buffer