name: Deploy Backend

on:
  push:
    branches: [ prod ]
    paths:
      - "backend/**"

jobs:
  deploy-backend:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and start backend
        run: |
          cd backend
          docker compose up -d --build